version: '3.9'

services:
  app:
    image: python:3.9
    container_name: llm_article_analyzer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./vectordb_init.sql:/docker-entrypoint-initdb.d/vectordb_init.sql
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: llm_article_analyzer

volumes:
  postgres_data:
